project:
  type: website
  resources:
    - "images/front-page-crop1.jpg"

website:
  title: "AIMS eReefs"
  favicon: images/ereefs_aims_favicon.png
  search: true
  navbar:
    background: light
    pinned: true
  page-footer:
    background: primary
    left: |
      Collaborators
      <br>[![](/images/logos/AIMS-210x49.png){fig-alt="AIMS"}](https://aims.gov.au/)
      [![](/images/logos/CSIRO-60x60.png){fig-alt="CSIRO"}](https://www.csiro.au/){style="height: 49px;"}
      [![](/images/logos/BoM-210x51.png){fig-alt="Bureau of Meteorology"}](http://www.bom.gov.au/){style="height: 49px;"}
    right: |
      Funders
      <br>![](/images/logos/dcceew_logo.svg){fig-alt="Department of Climate Change, Energy, the Environment and Water" style="height: 49px;"}
      ![](/images/logos/GBRF_1-210x66.png){fig-alt="Great Barrier Reef Foundation" style="height: 49px;"}
      ![](/images/logos/QLD-Gov-64x80.png){fig-alt="Queensland Government" style="height: 49px;"}
      ![](/images/logos/SIEF-110x66.png){fig-alt="Science and Industry Endowment Fund" style="height: 49px;"}


format:
  html:
    theme: 
      - flatly
      - css/custom.scss
    css: 
      - css/ereefs_aims.css
      - css/eatlas_ncanimate2.css
      - css/eatlas_ncanimate2_responsive.css
      - css/styles.css
    toc: false
    include-in-header:
      - javascript/remove_quarto_header.html
      - text: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap" rel="stylesheet">
      - text: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&family=Open+Sans&display=swap" rel="stylesheet">
    grid:
      body-width: 1220px
    mainfont: Open Sans

execute:
  freeze: auto # ensures code blocks are only executed locally as opposed to being executes as part of GitHub actions
