project:
  type: website
  resources:
    - "images/front-page-crop1.jpg"
    - "images/banner.jpg"

website:
  title: "AIMS eReefs Visualisation Portal"
  favicon: images/ereefs_aims_favicon.png
  search: true
  navbar:
    title: "eReefs"
    logo: https://www.ereefs.org.au/assets/images/logos/ereefs_logo.svg
    background: light
    pinned: false
    right:
      - href: https://www.ereefs.org.au/
        text: Home
      - text: About
        menu:
          - href: https://www.ereefs.org.au/research/
            text: About eReefs
          - href: about.qmd
            text: About AIMS eReefs
      - href: https://www.ereefs.org.au/research/
        text: Research
      - href: https://www.ereefs.org.au/tools/
        text: Tools
      - href: https://www.ereefs.org.au/contact/
        text: Contact
      - text: Help
        menu:
          - href: help/index.qmd
            text: Visualisation Portal Help
          - href: https://open-aims.github.io/ereefs-tutorials/
            text: Tutorials ![External Link](/images/External_link_font_awesome.svg){.external-link}
          - href: https://extraction.ereefs.aims.gov.au/faqs
            text: Data Extraction FAQs ![External Link](/images/External_link_font_awesome.svg){.external-link}
  page-footer:
    background: primary
    center:
      - text: Collaborators
        href: https://www.ereefs.org.au/about/collaborators.html
      - text: Funders
        href: https://www.ereefs.org.au/about/funders.html
      - text: Privacy Policy![External Link](/images/External_link_font_awesome.svg){.external-link}
        href: https://www.csiro.au/en/About/Access-to-information/Privacy
      - text: Legal & Disclaimer![External Link](/images/External_link_font_awesome.svg){.external-link}
        href: https://www.csiro.au/en/About/Footer/Legal-notice



format:
  html:
    theme: 
      - css/custom.scss
    css: 
      - css/ereefs_aims.css
      - css/ncanimate2.css
      - css/ncanimate2_responsive.css
      - css/styles.css
    toc: false
    include-in-header:
      - text: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700" rel="stylesheet">
      - text: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto" rel="stylesheet">
      - includes/_page_banner.html
    grid:
      body-width: 1300px
    mainfont: Open Sans
    fontcolor: "#212529"

execute:
  freeze: auto # ensures code blocks are only executed locally as opposed to being executes as part of GitHub actions
