project:
  type: website
  resources:
    - "images/front-page-crop1.jpg"
    - "images/banner.jpg"

website:
  title: "AIMS eReefs Visualisation Portal"
  favicon: images/ereefs_aims_favicon.png
  search: true
  navbar:
    title: "AIMS eReefs Visualisation Portal"
    logo: https://www.ereefs.org.au/assets/images/logos/ereefs_logo.svg
    background: light
    pinned: false
    left:
      - text: eReefs Websites
        menu:
          - href: https://www.ereefs.org.au/
            text: Project Overview ![External Link](/images/External_link_font_awesome.svg){.external-link}
          - href: https://research.csiro.au/ereefs/
            text: CSIRO Research Portal ![External Link](/images/External_link_font_awesome.svg){.external-link}
          - href: http://www.bom.gov.au/environment/activities/reeftemp/reeftemp.shtml
            text: ReefTemp ![External Link](/images/External_link_font_awesome.svg){.external-link}
          - href: https://portal.ereefs.info/
            text: Interactive Data Portal ![External Link](/images/External_link_font_awesome.svg){.external-link}
      - href: index.qmd
        text: Visualisation Portal
      - href: https://extraction.ereefs.aims.gov.au/?_gl=1*1ag9zj1*_ga*OTM5OTM3MTMzLjE2NjczNTcwNzg.*_ga_6SSTNBNHXG*MTY5MTk2OTEyOC4yNy4wLjE2OTE5NjkxMjguMC4wLjA.
        text: Data Extraction ![External Link](/images/External_link_font_awesome.svg){.external-link}
      - text: Help
        menu:
          - href: help/index.qmd
            text: Visualisation Portal Help
          - href: https://open-aims.github.io/ereefs-tutorials/
            text: Tutorials ![External Link](/images/External_link_font_awesome.svg){.external-link}
          - href: https://extraction.ereefs.aims.gov.au/faqs
            text: Data Extraction FAQs ![External Link](/images/External_link_font_awesome.svg){.external-link}
      - href: about.qmd
        text: About
  page-footer:
    background: primary
    left: |
      Collaborators
      <br>[![](/images/logos/AIMS-210x49.png){fig-alt="AIMS"}](https://aims.gov.au/)
      [![](/images/logos/CSIRO-60x60.png){fig-alt="CSIRO"}](https://www.csiro.au/){style="height: 49px;"}
      [![](/images/logos/BoM-210x51.png){fig-alt="Bureau of Meteorology"}](http://www.bom.gov.au/){style="height: 49px;"}
    right: |
      Funders
      <br>[![](/images/logos/dcceew_logo.svg){fig-alt="Department of Climate Change, Energy, the Environment and Water" style="height: 49px;"}](https://www.dcceew.gov.au/)
      [![](/images/logos/GBRF_1-210x66.png){fig-alt="Great Barrier Reef Foundation" style="height: 49px;"}](https://www.barrierreef.org/)
      [![](/images/logos/QLD-Gov-64x80.png){fig-alt="Queensland Government" style="height: 49px;"}](https://www.qld.gov.au/)
      [![](/images/logos/SIEF-110x66.png){fig-alt="Science and Industry Endowment Fund" style="height: 49px;"}](https://sief.org.au/)


format:
  html:
    theme: 
      - css/custom.scss
    css: 
      - css/ereefs_aims.css
      - css/ncanimate2.css
      - css/ncanimate2_responsive.css
      - css/styles.css
    toc: false
    include-in-header:
      - text: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap" rel="stylesheet">
      - text: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&family=Open+Sans&display=swap" rel="stylesheet">
      - includes/_page_banner.html
    grid:
      body-width: 1300px
    mainfont: Open Sans
    fontcolor: "#212529"

execute:
  freeze: auto # ensures code blocks are only executed locally as opposed to being executes as part of GitHub actions
